=== markelpastor/pbl_grupo_6/PBL6/web/20240517/xsdpacientes.xsd
<?xml version="1.0" encoding="UTF-8"?> 




<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="GlaucoDtect_analysis">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Patients">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Patient" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Hospital" type="xs:string"/>
										<xs:element name="Doctor" type="xs:string"/>
										<xs:element name="fecha_diagnÃ³stico" type="xs:date"/>
										<xs:element name="Glaucoma" type="xs:string"/>
										<xs:element name="Calidad_imagen" type="xs:string"/>
										<xs:element name="Resultados_imagenes">
											<xs:complexType>
												<xs:attribute name="image" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="[a-z]{3}[0-9]{4}[A-Z]"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== markelpastor/pbl_grupo_6/PBL6/web/20240517/xmldatos.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="pacientes.xslt"?>

<GlaucoDtect_analysis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsdpacientes.xsd">

	<Patients>

		<Patient id="akv0543N">
			<Hospital>Txagorritxu</Hospital>
			<Doctor>Dr. Alejandro Ramírez</Doctor>
			<fecha_diagnóstico>2022-05-06</fecha_diagnóstico>
			<Glaucoma>Si</Glaucoma>
			<Calidad_imagen>Calidad correcta</Calidad_imagen>
			<Resultados_imagenes image="calidadcorrecta.jpg"/>  
		</Patient>

		<Patient id="akv0543A">
			<Hospital>Cruces</Hospital>
			<Doctor>Dra. Laura Martínez</Doctor>				
			<fecha_diagnóstico>2024-05-06</fecha_diagnóstico>
			<Glaucoma>No</Glaucoma>
			<Calidad_imagen>Ruido</Calidad_imagen>
			<Resultados_imagenes image="ruido.jpg"/>  
		</Patient>

		<Patient id="akv0543P">
			<Hospital>Txagorritxu</Hospital>
			<Doctor>Dr. Carlos Fernández</Doctor>	
			<fecha_diagnóstico>2023-05-06</fecha_diagnóstico>
			<Glaucoma>No</Glaucoma>
			<Calidad_imagen>Bajo contraste</Calidad_imagen>
			<Resultados_imagenes image="bajocontraste.jpg"/>  
		</Patient>

	</Patients>

</GlaucoDtect_analysis>
